FROM ubuntu:xenial

WORKDIR /c2w

RUN apt-get update && apt-get install -y nodejs tmux dnsutils dnsmasq
COPY consul_0.6.4-1~xenial1~ppa1_amd64.deb .
RUN dpkg -i consul_0.6.4-1~xenial1~ppa1_amd64.deb
RUN echo "server=/consul/127.0.0.1#8600" > /etc/dnsmasq.d/10-consul
RUN echo "user=root" > /etc/dnsmasq.d/00-root

COPY ui.js .
COPY start_consul_agent.sh .
COPY start_ui.sh .

EXPOSE 8301

CMD sh start_consul_agent.sh $IP && sh start_ui.sh
